name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.22.0'

      - name: Show directory structure
        run: ls -R

      - name: Show current directory
        run: pwd

      - name: Install dependencies
        run: go mod tidy
        working-directory: ./cmd/api

#      - name: Run tests
#        run: go test ./...
#        working-directory: ./cmd/api

      - name: Build project
        run: GOOS=linux GOARCH=amd64 go build -o audioscript ./cmd/api
        working-directory: ./

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy files via SSH
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "audioscript"
          target: "~/audioscript"

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            pkill myapp || true
            nohup ./myapp &

